# Generated by Django 4.2.2 on 2023-06-23 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=60)),
                ('cantidad_personas', models.IntegerField()),
                ('duracion', models.CharField(max_length=30)),
                ('forma_pago', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.tipo'),
        ),
    ]
