# Generated by Django 4.2.2 on 2023-06-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_tipo_cliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='cantidad_personas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='duracion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='forma_pago',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre_evento',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
