# Generated by Django 4.2.2 on 2023-07-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_notific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notific',
            name='celular',
            field=models.CharField(max_length=10),
        ),
    ]
