# Generated by Django 4.2.2 on 2023-07-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_alter_notific_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='notific',
            name='notificacion',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
